apiVersion: v1
kind: Pod
metadata:
  name: fullapp-pod
spec:
  containers:
  - name: fullapp-container
    image: busybox
    command: ["sh", "-c", "echo ---APP CONFIG--- && echo $APP_ENV $APP_PORT $APP_COLOR && echo ---DATABASE--- && echo $DB_USER $DB_NAME && sleep 3600"]
    envFrom:
    - configMapRef:
        name: app-config
    - secretRef:
        name: db-secret